<script setup lang="ts">
// Account setup from the admin's link: password, then authenticator app or passkey.
type Step = 'loading' | 'invalid' | 'password' | 'factor' | 'totp' | 'codes';
const { set } = useSession();
const step = ref<Step>('loading');
const token = ref('');
const account = ref({ username: '', display_name: '', has_password: false });
const password = ref('');
const password2 = ref('');
const totp = ref({ qr_svg: '', secret: '', otpauth_url: '' });
const code = ref('');
const passkeyName = ref('');
const codes = ref<string[]>([]);
const error = ref('');
const busy = ref(false);
const canPasskey = ref(false);
let me: Me | null = null;

onMounted(async () => {
	canPasskey.value = passkeysSupported();
	const invite = location.hash.slice(1);
	// Remove the link from the address bar (history, screen sharing).
	history.replaceState(null, '', '/setup');
	if (!invite) {
		step.value = 'invalid';
		return;
	}
	try {
		const r = await apiPost<{
			setup_token: string;
			username: string;
			display_name: string;
			has_password: boolean;
		}>('/setup/start', { invite });
		token.value = r.setup_token;
		account.value = r;
		step.value = 'password';
	} catch (e) {
		error.value = errorMessage(e);
		step.value = 'invalid';
	}
});

async function attempt(fn: () => Promise<void>) {
	busy.value = true;
	error.value = '';
	try {
		await fn();
	} catch (e) {
		error.value = errorMessage(e);
	} finally {
		busy.value = false;
	}
}

const setPassword = () =>
	attempt(async () => {
		if (password.value !== password2.value) throw new Error('Die Passwörter stimmen nicht überein.');
		await apiPost('/setup/password', { setup_token: token.value, password: password.value });
		password.value = password2.value = '';
		step.value = 'factor';
	});

const startTotp = () =>
	attempt(async () => {
		totp.value = await apiPost('/setup/totp/begin', { setup_token: token.value });
		step.value = 'totp';
	});

function showCodes(r: { recovery_codes: string[]; me: Me }) {
	codes.value = r.recovery_codes;
	me = r.me;
	step.value = 'codes';
}

const confirmTotp = () =>
	attempt(async () => {
		showCodes(await apiPost('/setup/totp/confirm', { setup_token: token.value, code: code.value }));
	});

const addPasskey = () =>
	attempt(async () => {
		const begin = await apiPost<PasskeyBegin>('/setup/passkey/begin', {
			setup_token: token.value,
			name: passkeyName.value || 'Passkey'
		});
		const credential = await registerPasskey(begin.options);
		showCodes(
			await apiPost('/setup/passkey/finish', {
				setup_token: token.value,
				ceremony: begin.ceremony,
				credential
			})
		);
	});

async function finish() {
	set(me);
	await navigateTo('/');
}
</script>

<template>
	<main class="narrow with-scenery">
		<p class="brand-line"><span class="brand-mark" aria-hidden="true"></span>xlrx</p>
		<div class="card">
			<h1>Konto einrichten</h1>
			<p v-if="step === 'loading'" class="muted">Einen Moment …</p>
			<template v-else-if="step === 'invalid'">
				<p class="error">{{ error || 'Der Einrichtungslink fehlt oder ist ungültig.' }}</p>
				<p class="muted">Bitte bei der Person nachfragen, die das Konto verwaltet.</p>
			</template>
			<template v-else-if="step === 'password'">
				<p>
					Willkommen, {{ account.display_name }}! Benutzername: <strong>{{ account.username }}</strong>
				</p>
				<form @submit.prevent="setPassword">
					<label for="p1">Neues Passwort (mindestens 12 Zeichen)</label>
					<input id="p1" v-model="password" type="password" autocomplete="new-password" minlength="12" required />
					<label for="p2">Passwort wiederholen</label>
					<input id="p2" v-model="password2" type="password" autocomplete="new-password" required />
					<p class="muted">Tipp: Ein Satz aus mehreren Wörtern ist leicht zu merken und schwer zu erraten.</p>
					<button class="primary full" :disabled="busy">Weiter</button>
				</form>
			</template>
			<template v-else-if="step === 'factor'">
				<p>
					Jede Anmeldung braucht einen zweiten Faktor. Wähle mindestens einen – später lassen sich weitere
					hinzufügen.
				</p>
				<template v-if="canPasskey">
					<label for="pkname">Name des Geräts</label>
					<input id="pkname" v-model="passkeyName" placeholder="z.B. iPhone, MacBook" />
					<button class="primary full" :disabled="busy" @click="addPasskey">
						Passkey einrichten (Face ID, Touch ID)
					</button>
					<div class="divider">oder</div>
				</template>
				<button class="full" :disabled="busy" @click="startTotp">Authenticator-App einrichten</button>
			</template>
			<template v-else-if="step === 'totp'">
				<p>Den QR-Code mit der Authenticator-App scannen (z.B. Apple Passwörter, 2FAS, Aegis, 1Password).</p>
				<!-- SVG generated by the server from the otpauth URL; contains no user input as markup. -->
				<div class="qr" v-html="totp.qr_svg"></div>
				<p class="muted">Oder den Schlüssel eingeben: <span class="code">{{ totp.secret }}</span></p>
				<form @submit.prevent="confirmTotp">
					<label for="c">Angezeigter Code</label>
					<input id="c" v-model="code" class="code" inputmode="numeric" autocomplete="one-time-code" required />
					<button class="primary full" :disabled="busy">Bestätigen</button>
				</form>
			</template>
			<RecoveryCodes v-else-if="step === 'codes'" :codes="codes" @done="finish" />
			<p v-if="error && step !== 'invalid'" class="error" role="alert">{{ error }}</p>
		</div>
		<Landscape class="scenery" />
	</main>
</template>
